set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if (NOT DEFINED CMAKE_C_COMPILER)
    if (DEFINED ENV{AERO_CC_LINUX_ARM64})
        set(CMAKE_C_COMPILER "$ENV{AERO_CC_LINUX_ARM64}" CACHE FILEPATH "C compiler for linux-arm64" FORCE)
    else()
        set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc CACHE FILEPATH "C compiler for linux-arm64" FORCE)
    endif()
endif()

if (NOT DEFINED CMAKE_CXX_COMPILER)
    if (DEFINED ENV{AERO_CXX_LINUX_ARM64})
        set(CMAKE_CXX_COMPILER "$ENV{AERO_CXX_LINUX_ARM64}" CACHE FILEPATH "CXX compiler for linux-arm64" FORCE)
    else()
        set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++ CACHE FILEPATH "CXX compiler for linux-arm64" FORCE)
    endif()
endif()
